log_level = "warn"
outputs = { Targets = ["DP-1", "HDMI-A-2"] }
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ [ "Updates", "Workspaces", "WindowTitle" ] ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
font_name="Hack"
style = "Islands"
opacity=0.3
primary_color = "#4a4a4a"
success_color = "#9ece6a"
text_color = "#eeeeee"
workspace_colors = [ "#2d2d2d" ]
special_workspace_colors = ["#2d2d2d"]
[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1f1f1f"
weak = "#3d3d3d"
strong = "#636363"

[appearance.secondary_color]
base = "#3d3d3d"

[appearance.menu]
opacity=0.4
backdrop=0.3
